FROM node:20

WORKDIR /app

COPY . .

RUN corepack enable && corepack prepare pnpm@8.10.5 --activate
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @supavec/web... install
RUN pnpm --filter @supavec/web build

EXPOSE 3000
CMD ["pnpm", "--filter", "@supavec/web", "start"]
